### ISSUE TITLE
开启Chinese Exhentai之后搜索不到本子

### ISSUE THREAD

**Issue by hstonc** [nonpricklycactus/Ehentai_metadata#11]
开启Chinese Exhentai之后搜索不到本子
Calibre版本:6.21
插件版本:2.3.2
系统:Ubuntu22.04
EhTagTranslation.db存放在:/home/gg/下載/EhTagTranslation.db
指定的目录是:/home/gg/下載
```
calibre, version 6.21.0
錯誤： 未發現符合項目: <p>找不到任何符合您的搜尋的書本。試著把搜尋條件<b>放寬</b>。例如，只使用作者的姓氐和書名中的單一個字詞。<p>要查看完整紀錄，請點選 「顯示詳細資料」

Running identify query with parameters: 
{'title': '[空色れん] 長門を森で後ろから… (アズールレーン)', 'authors': ['空色れん'], 'identifiers': {}, 'timeout': 30} 
Using plugins: E-hentai Galleries (2, 3, 2) 
The log from individual plugins is below 

****************************** E-hentai Galleries (2, 3, 2) ****************************** 
Found 0 results 
Downloading from E-hentai Galleries took 0.8630654811859131 
Failed to get gallery_id and gallery_token!
NoneType: None

Plugin E-hentai Galleries failed
Traceback (most recent call last):
  File "calibre/ebooks/metadata/sources/identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 712, in identify
    if len(gidlist) != 0:
TypeError: object of type 'NoneType' has no len() 

******************************************************************************** 
The identify phase took 1.00 seconds 
The longest time (0.863065) was taken by: E-hentai Galleries 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds 
```

**Comment by nonpricklycactus** [comment]
这个是正常的 只是《[空色れん] 長門を森で後ろから… (アズールレーン)》没有搜到所以流程中断  你可以尝试在E站手动搜到然后使用 Accurate_Label功能
